/** @format */

const mediatypes = {
	GET_HOME_PAGE_PLAYLISTS: 'GET_HOME_PAGE_PLAYLISTS',
	SET_CURRENT_PLAYLIST: 'SET_CURRENT_PLAYLIST',
	PLAY: 'PLAY',
	SEARCH_ALBUM: 'SEARCH_ALBUM',
	SEARCH_TRACK: 'SEARCH_TRACK',
	SEARCH_PLAYLIST: 'SEARCH_PLAYLIST',
};

export default mediatypes;
